In [1]:
import numpy as np
import pandas as pd
import random
from dswe import BayesTreePowerCurve

## Verifying SVMPowerCurve outputs with R outputs on a random input

In [9]:
X_train = np.arange(1,17).reshape(4, 4).T
y_train = np.arange(17,21)
X_test = X_train

In [10]:
clf = BayesTreePowerCurve(X_train, y_train)
pred = clf.predict(X_test)

  0%|          | 1/200 [00:00<00:40,  4.97it/s]/opt/homebrew/Caskroom/miniforge/base/envs/condapy/lib/python3.9/site-packages/bartpy/samplers/unconstrainedtree/likihoodratio.py:93: RuntimeWarning: invalid value encountered in log
  prob_grow_node_selected = - np.log(n_splittable_leaf_nodes(tree) - 1)


Starting burn
Starting burn
Starting burn
Starting burn


  2%|▏         | 3/200 [00:00<00:08, 22.90it/s]

Starting sampling
Starting sampling
Starting sampling
Starting sampling


100%|██████████| 200/200 [00:09<00:00, 21.72it/s]


In [11]:
## R outputs: [1] 17 18 19 20

pred

array([17.02855798, 18.0016711 , 18.99868008, 19.97206233])

## Verifying SVMPowerCurve outputs with R on a wind dataset

In [2]:
df = pd.read_csv('../../Inland_Offshore_Wind_Farm_Dataset1/Inland Wind Farm Dataset1(WT1).csv')
X_train = df.iloc[:100, [1,2,3,4]].values
y_train = df.iloc[:100, 6].values
X_test = df.iloc[100:110, [1,2,3,4]].values
y_test = df.iloc[100:110, 6].values

In [5]:
random.seed(1)
clf = BayesTreePowerCurve(X_train, y_train)
pred = clf.predict(X_test)

Starting burn


  0%|          | 0/200 [00:00<?, ?it/s]8.96it/s]

Starting burn
Starting burn
Starting burn


 96%|█████████▌| 191/200 [00:10<00:00, 19.93it/s]

Starting sampling


  0%|          | 0/200 [00:00<?, ?it/s]

Starting sampling
Starting sampling
Starting sampling


100%|██████████| 200/200 [00:10<00:00, 19.31it/s]


In [4]:
## R outputs: [1]  4.489055  5.145760  3.918824  4.506029  4.548529  5.949380  5.885395 10.575446 10.136648 11.625397
##            [1]  4.908871  5.261199  3.838104  4.550532  4.532476  5.396801  5.896479  9.715911  9.319047  9.873712      
## (ran 2 times)

pred

array([ 5.41647362,  5.53352227,  4.09661889,  5.24522169,  4.56662173,
        3.99310857,  7.70507665, 12.47277589, 10.89936482, 13.15729743])

In [6]:
pred

array([ 5.65334398,  6.08692851,  4.23905672,  5.19493545,  4.87002943,
        5.11559125,  7.59129997, 10.59236674, 10.20951398, 11.63146463])

In [7]:
# 4.815239  5.121856  3.693283  5.176517  4.080357  5.260815  6.063750 10.747272 10.241911 11.064810